site_name: Valist Documentation
theme: 
  name: material
  features:
    - toc.integrate
nav:
    - index.md
    - creating-an-organization.md
    - creating-a-repository.md
    - access-control.md
    - multi-factor-everything.md
    - publishing-software.md
    - fetching-and-installing-software.md
markdown_extensions:
  - attr_list
  - pymdownx.highlight
  - pymdownx.inlinehilite

